### ISSUE TITLE
Adding aur as a install option

### ISSUE THREAD

**Issue by Juliaria08** [NNBnh/mk#1]
Hi, what name sould i put it under?
- It needs to end with `-git`
- It cloud not be `mk-git`, but cloud be `superbmk-git` also planning to do it for more of these single file applications
Waiting for your feedback

**Comment by NNBnh** [comment]
Thank you @Juliaria08 for spending time port SuperB MK to the AUR.

> It cloud not be `mk-git`, but cloud be `superbmk-git`

Yeah, about the name: "superbmk-git" would be the best.

**Comment by Juliaria08** [comment]
It works with manual makepkg -si so it should work, done
I dont know why it does not work with `yay`.
